workflows:
  android-build:
    name: Build Monad APK
    max_build_duration: 60
    environment:
      flutter: false
      vars:
        ANDROID_KEYSTORE_BASE64: EncryptedKeystoreHere   # optional if you sign release
    scripts:
      - name: Checkout repository
        script: |
          git clone https://github.com/Abenether160/Monad.git
          cd Monad
      - name: Build APK
        script: |
          cd Monad/app
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        on_build_success: true
        on_build_failure: true