workflows:
  android-release-build:
    name: Build Monad Release APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_BASE64: EncryptedKeystoreHere   # Base64 of your keystore file
        ANDROID_KEYSTORE_PASSWORD: YourKeystorePassword
        ANDROID_KEY_ALIAS: YourKeyAlias
        ANDROID_KEY_PASSWORD: YourKeyPassword
    scripts:
      - name: Build release APK
        script: |
          cd app
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        on_build_success: true
        on_build_failure: true
