workflows:
  android-release-build:
    name: Android Release Build
    max_build_duration: 60
    environment:
      vars:
        KEYSTORE_BASE64: >
          "MIIKygIBAzCCCnQGCSqGSIb3DQEHAaCCCmUEggphMIIKXTCCBbQGCSqGSIb3DQEHAaCCBaUEggWh
          MIIFnTCCBZkGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUM
          ... (rest of your base64) ...
          ICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEKGCc4ODwoLpXMfsNZ3+atSAggQQAM
          +gSeqsfJ7LX82UAeTg6s36DntLwqoWYSegAdhx6k/CAjpft1Q8du62Oo9bRsPEqEhLq+/87GQPMZm
          uBtxnuflpYo7Vf44ZTyta9ippfJVaWFuUBAGclzKIuYhm7bGUsMc+onhv2D0aL1+A1s23sIsVh+Q
          MadYKQHNca98EET4/mkYJzrW07X0vimVUZm8qenY5XyhLM1vdWQtXSUKjbfFYWisbMzd15xQlOPp
          CjZtnNqFw9TkPSulqVLBZCAqu659G9Hcf5NTzRQHaRQA1Lw/vWTUEXAIhvX3ie+vavwSfWep5nNT
          DITUA03UvNvIKASXhJhMlmRy3++LSWSyoYZoAPe3pIu5qDbLOJeNVSZgsvUuZGSaj9w/v9vEv5+j
          +A0xWdBN2Xls3jVt1Uu3lvJwQtcEL/NGXqRSLpqT9tHK8vgPRDa/TagDkInlS7g6+fHALJfJuTlkc
          NBiF6ENJix7DIRbV7/Pj8o2k/vV/i3jBt7KLdury1nAGKl8G3O1tqpX+FFjQEjRil3c1uSdqku1M
          bkIHW3WYOB3tTiyAbZ3w0Wn6No2LPO/gBdwA1hFEpt8yOpN4aJnMQgsyHXhDNv1W3Fojm55NSVEr
          TOKMmUaznuokaj2FzaachDnsvKQgtLl48vGSskCYcV9gKvAkM2Mg1EmlhEMuvVhg4gdbD600t+SE
          AeCJTYESsvaL137fOFg7stVIBnsFMygU+BpNKCmcrXTgds3VA4uIgTO91stJLAkqPA872yKgyZ8S
          ky1elk0eiDnUw0pfSJAqxmHenfmlDbQWXpIOGAML86RsGniZJ5ewaK3sOLeZ7GWlppLH9P5vOrsA
          /IrAZb1JJRaiqHNyOqEPIrVEbgRf2XVHaMNgWcaXHFukk+t0k/tqYxIMPu0xjUns6Z7P3tm5jaXr
          M2JsjkOT1jTAKtF3Qal5bsQS+fkf4Hnuk95oHaK0dsQo5OBBXsl6XxkvFK8HudHDqJw4uGDvKI/H
          ARaXjqZobN1cZWbFnQjTGxMa7vN8ggeYJwOV6TRg9czl9hm5Qsc585gdymyxYVIUutDrhdhRwhyF
          eDvc1/oH1Zq6L3x2c8OD5aGTN4qspI8dwoAOAxxEeb31mEyonP7uJnl3EI8NyBsRA2WeGpYbfHda
          57hWAMkst1IEabXucj2iEO63FB82olzm4OI9eix/1MwLwEVxmUwYchWgzwcijLBl7TNyERJFOvQd
          w+IunrnJVB1kXlQcORsKxhtHPrQyRs2QkrGBf+fXi8vjSK3riWFABRJzzSukEQdJ32fiGf0tmkUn
          Mta3FGJ8aoaejwbqGvKhDgsb2+xLiDYeWqXHKWmrytq7T36NYkOkQJYSmDwYt/CFS9hOliPM/GE/
          4IBxSOp7oNAAdrEwTTAxMA0GCWCGSAFlAwQCAQUABCB7nwmhPUIiKOMwtYy3BQ0rg2EIIUwoDD1H
          089Ze7TREgQUxtncXB8gHu+f/ekf7XWOixUgk70CAicQ"

    scripts:
      - name: Decode keystore
        script: |
          #!/usr/bin/env bash
          mkdir -p android/app
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/monad.keystore
          
      - name: Build release APK
        script: |
          ./gradlew assembleRelease -p android
